brightness: 63
SubnetID1: 0
SubnetID2: 0
SubnetID3: 0
SubnetID4: 0
SubnetID5: 0
SubnetID6: 0
SubnetID7: 0
SubnetID8: 0
UniverseID1: 1
UniverseID2: 2
UniverseID3: 3
UniverseID4: 4
UniverseID5: 5
UniverseID6: 6
UniverseID7: 7
UniverseID8: 8
